alertmanager:
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
        release: monitoring
    replicas: 2
    alertmanagerConfigMatcherStrategy:
      type: None

prometheus:
  service:
    type: NodePort
    nodePort: 30090

grafana:
  service:
    type: NodePort
    nodePort: 30003