# aura-infra/apps/aura-k8s-chat-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aura-k8s-chat-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Richard-m-j/aura-k8s-chat.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: aura-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true