# aura-infra/apps/backend-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # The name of this Argo CD Application resource
  name: backend-app
  # Argo CD resources must be in the 'argocd' namespace
  namespace: argocd
  # Finalizer to ensure resources are cleaned up when this app is deleted
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project this application belongs to
  project: default
  source:
    # The URL of the microservice's Git repository
    repoURL: https://github.com/Richard-m-j/kube-openWebUI-backend.git
    # The branch to track
    targetRevision: main
    # The path within the repository where the Kubernetes manifests are located
    path: kubernetes
  destination:
    # Deploy to the same cluster where Argo CD is running
    server: https://kubernetes.default.svc
    # The target namespace for the application workloads
    namespace: open-webui-app
  syncPolicy:
    # Enable automated synchronization
    automated:
      # Automatically delete resources that are no longer defined in Git
      prune: true
      # Automatically sync when the application is out-of-sync
      selfHeal: true
    syncOptions:
      # Automatically create the destination namespace if it doesn't exist
      - CreateNamespace=true