name: Trigger AI Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required for the action to comment on PRs
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - name: 2. Generate Diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > code.diff

      - name: 3. Run AI Code Review
        uses: richard-m-j/code-turtle@main # Replace with your action's repository and version
        with:
          pr_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          model_url: 'https://huggingface.co/unsloth/Qwen3-4B-Instruct-2507-GGUF/resolve/main/Qwen3-4B-Instruct-2507-Q5_K_M.gguf'