name: Deploy ArgoCD Infra

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run setup script
      run: |
        chmod +x terraform/setup.sh
        cd terraform
        ./setup.sh