name: Deploy EC2 Instance with Terraform

on:
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"
  TF_VERSION: "1.5.7"

jobs:
  terraform-deploy:
    name: 'Terraform Deploy EC2'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Configure your AWS credentials from GitHub secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }} # Corrected secret name
          aws-region: us-east-1 # Important: Change this to the region of your AMI

      # Step 3: Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'

      # Step 4: Initialize Terraform in the correct directory
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./terraform

      # Step 5: Create a Terraform Plan in the correct directory
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./terraform

      # Step 6: Apply the Terraform changes from the correct directory
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./terraform